# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0002_group_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='DC1E57F4FE04D52', max_length=15),
        ),
    ]
