# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0002_auto_20171207_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='profile',
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='CrTaZ00', max_length=15),
        ),
    ]
