# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0003_auto_20171202_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='rfvbbzpuz5pykersjpao', max_length=15),
        ),
    ]
