# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0004_auto_20171202_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='srob18s', max_length=15),
        ),
    ]
