# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0005_auto_20171202_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='address',
            field=models.CharField(default='wO6q', max_length=15),
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='Y9oXc', max_length=15),
        ),
    ]
