# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0009_auto_20171202_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='AUECC8d', max_length=15),
        ),
    ]
