# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0010_auto_20171202_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='list',
            name='parent',
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='n7ORXFg', max_length=15),
        ),
    ]
