# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0011_auto_20171202_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='group_address',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='oAoy5fd', max_length=15),
        ),
    ]
