# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas', '0013_auto_20171202_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='group_address',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='address',
            field=models.CharField(default='cxa46Yh', max_length=15),
        ),
    ]
